# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4810357e58dca30bae1aa324a573f20d"
name = "Cipherpay"
application_url = "https://custom.cipherpay.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://custom.cipherpay.app/api/auth/callback" ]
